board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('mypage/', views.MypageView.as_view(), name="mypage"),
    path('kyoumu/', views.KyoumuView.as_view(), name="board_kyoumu"),
    path('gakusei/', views.GakuseiView.as_view(), name="board_gakusei"),
    path('shien/', views.ShienView.as_view(), name="board_shien"),
    path('arubaito/', views.ArubaitoView.as_view(), name="board_arubaito"),
    path('gakuyu/', views.GakuyuView.as_view(), name="board_gakuyu"),
    path('job/', views.JobView.as_view(), name="board_job"),
    path('post-detail/<int:pk>/', views.PostDetailView.as_view(), name="post_detail"),
    path('post-create/', views.PostCreateView.as_view(), name="post_create"),
    path('post-update/<int:pk>/', views.PostUpdateView.as_view(), name="post_update"),
    path('post-delete/<int:pk>/', views.PostDeleteView.as_view(), name="post_delete"),
]

campus_board/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path
from django.conf.urls import include

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

board/models.py
from django.db import models
from accounts.models import CustomUser

import os

class Board(models.Model):
	"""掲示板モデル"""
	board_name = models.CharField(verbose_name='掲示板名', max_length=256)
	board_img = models.ImageField(verbose_name='デフォルト画像', null=True, blank=True)
	def __str__(self):
		return self.board_name
		
class GradeTag(models.Model):
	"""学年タグモデル"""
	name = models.CharField(verbose_name='学年', max_length=256)
	def __str__(self):
		return self.name
		
class DepartmentTag(models.Model):
	"""学科タグモデル"""
	name = models.CharField(verbose_name='学科', max_length=256)
	def __str__(self):
		return self.name
		
class TypeTag(models.Model):
	"""種別タグモデル"""
	name = models.CharField(verbose_name='種別', max_length=256)
	def __str__(self):
		return self.name

class Post(models.Model):
	"""掲示物モデル"""
	board = models.ForeignKey(Board, verbose_name='掲示板名', on_delete=models.PROTECT)
	post_title = models.CharField(verbose_name='タイトル', max_length=256)
	post_overview = models.TextField(verbose_name='概要', null=True)
	started_at = models.DateTimeField(verbose_name='掲載開始', auto_now_add=True)
	ended_at = models.DateTimeField(verbose_name='掲載終了')
	post_photo = models.ImageField(verbose_name='写真', null=True, blank=True)
	post_upload = models.FileField(verbose_name='ファイル', upload_to='file/%y/%m/%d', null=True, blank=True)
	gradetags = models.ManyToManyField(GradeTag, verbose_name='学年')
	departmenttags = models.ManyToManyField(DepartmentTag, verbose_name='学科')
	typetags = models.ManyToManyField(TypeTag, verbose_name='種別')
	user_name = models.ForeignKey(CustomUser, verbose_name='投稿者', on_delete=models.CASCADE)
	def __str__(self):
		return self.post_title
		
	def file_name(self):
		return os.path.basename(self.post_upload.name)

board/forms.py
from django import forms
from django.utils import timezone

from .models import Post, GradeTag, DepartmentTag, TypeTag

class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('board', 'post_title', 'post_overview', 'ended_at', 'post_photo', 'post_upload', 'gradetags', 'departmenttags', 'typetags')

board/views.py
from django import forms
from django.views import generic
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Board, Post, GradeTag, DepartmentTag, TypeTag, CustomUser

from .forms import PostCreateForm


class IndexView(LoginRequiredMixin, generic.ListView):
    model = Post
    template_name = 'index.html'
    paginate_by = 6
    
    # get_context_data関数をオーバーライド
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        # 2つ目のモデルを指定
        ctx["board"] = Board.objects.all()
        ctx["gradetags"] = GradeTag.objects.all()
        ctx["departmenttags"] = DepartmentTag.objects.all()
        ctx["typetags"] = TypeTag.objects.all()
        ctx['search_form'] = PostSearchFormTop(self.request.GET)
        return ctx
        
    queryset = Post.objects.order_by(
        '-started_at'
    )
    
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        if self.request.GET.get('board'):
            queryset = queryset.filter(
                board=self.request.GET.get('board')
            )
        if self.request.GET.get('gradetags'):
            queryset = queryset.filter(
                gradetags=self.request.GET.get('gradetags')
            )
        if self.request.GET.get('departmenttags'):
            queryset = queryset.filter(
                departmenttags=self.request.GET.get('departmenttags')
            )
        if self.request.GET.get('typetags'):
            queryset = queryset.filter(
                typetags=self.request.GET.get('typetags')
            )
            
        return queryset
        
class PostSearchFormTop(forms.Form):
    board = forms.fields.ChoiceField(
        label='掲示板',
        choices=(
            ('', '未設定'),
            ('1', '教務課'),
            ('2', '学生課'),
            ('3', '学生支援担当'),
            ('4', 'アルバイト'),
            ('5', '学友会'),
            ('6', '就職課'),
        ),
        required=False,
        widget=forms.widgets.Select
    )
    gradetags = forms.fields.ChoiceField(
        label='学年',
        choices=(
            ('', '未設定'),
            ('1', '1学年'),
            ('2', '2学年'),
            ('3', '3学年'),
            ('4', '4学年'),
        ),
        required=False,
        widget=forms.widgets.Select
    )
    departmenttags = forms.fields.ChoiceField(
        label='学科',
        choices=(
            ('', '未設定'),
            ('1', '機械工学コース'),
            ('2', '電気電子通信工学コース'),
            ('3', 'システム情報工学コース'),
            ('4', '生命環境科学コース'),
            ('5', '建築・土木工学コース'),
            ('6', '感性デザイン学科'),
            ('7', '大学院'),
        ),
        required=False,
        widget=forms.widgets.Select
    )
    typetags = forms.fields.ChoiceField(
        label='種別',
        choices=(
            ('', '未設定'),
            ('', '--全般--'),
            ('1', '連絡事項'),
            ('', '--アルバイト--'),
            ('2', '長期'),
            ('3', '短期'),
        ),
        required=False,
        widget=forms.widgets.Select
    )
    
class KyoumuView(LoginRequiredMixin, generic.ListView):
    model = Post
    template_name = 'board_kyoumu.html'
    paginate_by = 6
    
    # get_context_data関数をオーバーライド
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        # 2つ目のモデルを指定
        ctx["board"] = Board.objects.all()
        ctx["gradetags"] = GradeTag.objects.all()
        ctx["departmenttags"] = DepartmentTag.objects.all()
        ctx["typetags"] = TypeTag.objects.all()
        ctx['search_form'] = PostSearchFormDetail(self.request.GET)
        return ctx

    queryset = Post.objects.filter(board=1).order_by('-started_at')
    
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        if self.request.GET.get('gradetags'):
            queryset = queryset.filter(
                gradetags=self.request.GET.get('gradetags')
            )
        if self.request.GET.get('departmenttags'):
            queryset = queryset.filter(
                departmenttags=self.request.GET.get('departmenttags')
            )
        if self.request.GET.get('typetags'):
            queryset = queryset.filter(
                typetags=self.request.GET.get('typetags')
            )
            
        return queryset
        
class PostSearchFormDetail(forms.Form):
    gradetags = forms.fields.ChoiceField(
        label='学年',
        choices=(
            ('', '未設定'),
            ('1', '1学年'),
            ('2', '2学年'),
            ('3', '3学年'),
            ('4', '4学年'),
        ),
        required=False,
        widget=forms.widgets.Select
    )
    departmenttags = forms.fields.ChoiceField(
        label='学科',
        choices=(
            ('', '未設定'),
            ('1', '機械工学コース'),
            ('2', '電気電子通信工学コース'),
            ('3', 'システム情報工学コース'),
            ('4', '生命環境科学コース'),
            ('5', '建築・土木工学コース'),
            ('6', '感性デザイン学科'),
            ('7', '大学院'),
        ),
        required=False,
        widget=forms.widgets.Select
    )
    typetags = forms.fields.ChoiceField(
        label='種別',
        choices=(
            ('', '未設定'),
            ('', '--全般--'),
            ('1', '連絡事項'),
            ('', '--アルバイト--'),
            ('2', '長期'),
            ('3', '短期'),
        ),
        required=False,
        widget=forms.widgets.Select
    )

class GakuseiView(LoginRequiredMixin, generic.ListView):
    model = Post
    template_name = 'board_gakusei.html'
    paginate_by = 6
    
    # get_context_data関数をオーバーライド
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        # 2つ目のモデルを指定
        ctx["board"] = Board.objects.all()
        ctx["gradetags"] = GradeTag.objects.all()
        ctx["departmenttags"] = DepartmentTag.objects.all()
        ctx["typetags"] = TypeTag.objects.all()
        ctx['search_form'] = PostSearchFormDetail(self.request.GET)
        return ctx

    queryset = Post.objects.filter(board=2).order_by('-started_at')
    
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        if self.request.GET.get('gradetags'):
            queryset = queryset.filter(
                gradetags=self.request.GET.get('gradetags')
            )
        if self.request.GET.get('departmenttags'):
            queryset = queryset.filter(
                departmenttags=self.request.GET.get('departmenttags')
            )
        if self.request.GET.get('typetags'):
            queryset = queryset.filter(
                typetags=self.request.GET.get('typetags')
            )
            
        return queryset

class ShienView(LoginRequiredMixin, generic.ListView):
    model = Post
    template_name = 'board_shien.html'
    paginate_by = 6
    
    # get_context_data関数をオーバーライド
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        # 2つ目のモデルを指定
        ctx["board"] = Board.objects.all()
        ctx["gradetags"] = GradeTag.objects.all()
        ctx["departmenttags"] = DepartmentTag.objects.all()
        ctx["typetags"] = TypeTag.objects.all()
        ctx['search_form'] = PostSearchFormDetail(self.request.GET)
        return ctx

    queryset = Post.objects.filter(board=3).order_by('-started_at')
    
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        if self.request.GET.get('gradetags'):
            queryset = queryset.filter(
                gradetags=self.request.GET.get('gradetags')
            )
        if self.request.GET.get('departmenttags'):
            queryset = queryset.filter(
                departmenttags=self.request.GET.get('departmenttags')
            )
        if self.request.GET.get('typetags'):
            queryset = queryset.filter(
                typetags=self.request.GET.get('typetags')
            )
            
        return queryset

class ArubaitoView(LoginRequiredMixin, generic.ListView):
    model = Post
    template_name = 'board_arubaito.html'
    paginate_by = 6
    
    # get_context_data関数をオーバーライド
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        # 2つ目のモデルを指定
        ctx["board"] = Board.objects.all()
        ctx["gradetags"] = GradeTag.objects.all()
        ctx["departmenttags"] = DepartmentTag.objects.all()
        ctx["typetags"] = TypeTag.objects.all()
        ctx['search_form'] = PostSearchFormDetail(self.request.GET)
        return ctx

    queryset = Post.objects.filter(board=4).order_by('-started_at')
    
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        if self.request.GET.get('gradetags'):
            queryset = queryset.filter(
                gradetags=self.request.GET.get('gradetags')
            )
        if self.request.GET.get('departmenttags'):
            queryset = queryset.filter(
                departmenttags=self.request.GET.get('departmenttags')
            )
        if self.request.GET.get('typetags'):
            queryset = queryset.filter(
                typetags=self.request.GET.get('typetags')
            )
            
        return queryset

class GakuyuView(LoginRequiredMixin, generic.ListView):
    model = Post
    template_name = 'board_gakuyu.html'
    paginate_by = 6
    
    # get_context_data関数をオーバーライド
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        # 2つ目のモデルを指定
        ctx["board"] = Board.objects.all()
        ctx["gradetags"] = GradeTag.objects.all()
        ctx["departmenttags"] = DepartmentTag.objects.all()
        ctx["typetags"] = TypeTag.objects.all()
        ctx['search_form'] = PostSearchFormDetail(self.request.GET)
        return ctx

    queryset = Post.objects.filter(board=5).order_by('-started_at')
    

board/templates/base.html
{% load static %}
{% load widget_tweaks %}

<!doctype html>
<html lang="ja" data-bs-theme="auto">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <title>{% block title %}{% endblock %}</title>

  <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" type="text/css">

  {% block head %}
  {% endblock %}
</head>

<body>
  <header data-bs-theme="light">
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container">
        <a href="{% url 'board:index' %}" class="navbar-brand d-flex align-items-center">
          <strong>学内掲示板</strong>
        </a>
        {% block header %}
        {% endblock %}
      </div>
    </div>
  </header>

  <main>
    <div class="board-container">
      <section class="py-5 container">
        <div class="row py-lg-5 text-center">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">{% block board-title %}{% endblock %}</h1>
            {% block mypage %}{% endblock %}
          </div>
          {%if messages%}
          <ul class="messages">
            {% for message in messages %}
            <div{% if message.tags %} class="my-3 alert alert-{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show"{% endif %} role="alert">
              {{ message }}
            </div>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        {% block contents %}
          {% block nav %}
          {% endblock %}
        {% endblock %}
    </div>
  </main>

  <!-- フッターに書く内容を決める -->
  <footer class="text-body-secondary py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">ページトップへ</a>
      </p>
    </div>
  </footer>

</body>

</html>

board/templates/board_arubaito.html
{% extends 'base.html' %}

{% load static %}

{% block title %}学内掲示板 - アルバイト{% endblock %}

{% block header %}
<div class="col-md-3 text-end">
    {% if user.is_authenticated %}
    {% if request.user.is_staff %}
    <a href="{% url 'board:post_create' %}" class="btn btn-primary float-right">新規作成</a>
    {% endif %}
    <a href="{% url 'account_logout' %}" class="btn btn-primary float-right">LOG OUT</a>
    {% else %}
    <a href="{% url 'account_login' %}" class="btn btn-primary float-right">LOG IN</a>
    {% endif %}
</div>
{% endblock %}

{% block board-title %}アルバイト{% endblock %}

{% block contents %}
    <div class="container text-center">
        <div class="row justify-content-md-center">
            <div class="col-md-10">
                <div class="alert alert-secondary" role="alert">
                    <div class="mb-3">
                        <label for="exampleSelect" class="form-label">掲示板リスト</label>
                        {% block nav %}
                        <ul class="list-unstyled">
                            <li><a href="{% url 'board:index' %}" title="掲示板トップ" class="text-decoration-none">掲示板トップ</a></li>
                            <li><a href="{% url 'board:board_kyoumu' %}" title="教務課" class="text-decoration-none">教務課</a></li>
                            <li><a href="{% url 'board:board_shien' %}" title="学生支援担当" class="text-decoration-none">学生支援担当</a></li>
                            <li><a href="{% url 'board:board_job' %}" title="就職課" class="text-decoration-none">就職課</a></li>
                            <li><a href="{% url 'board:board_gakusei' %}" title="学生課" class="text-decoration-none">学生課</a></li>
                            <li><a href="{% url 'board:board_gakuyu' %}" title="学友会" class="text-decoration-none">学友会</a></li>
                        </ul>
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-10">
                <div class="alert alert-secondary" role="alert">
                    <div class="mb-3">
                        <label for="exampleSelect" class="form-label">検索メニュー</label>
                        <form method="GET" class="post-form">
                            {% csrf_token %}
                            {{ search_form.as_p }}
                            <input type="submit" value="検索">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="board py-5 bg-body-tertiary">
        <div class="container">
            <div class="post-title text-center">
                <p>掲示物一覧</p>
            </div>
            <div class="row row-cols-1 row-cols-md-2 g-2">
                {% for post in post_list %}
                <div class="col">
                    <div class="card text-center">
                        <div class="card-header">
                            {{ post.board }}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">
                                {{ post.post_title }}
                            </h5>
                            <p class="card-text">
                                {{ post.post_overview|truncatechars:20 }}
                            </p>
                            <a href="{% url 'board:post_detail' post.pk %}" class="btn btn-primary">詳細表示</a>
                        </div>
                        <div class="card-footer text-body-secondary">
                            {{ post.started_at }}
                        </div>
                    </div>
                </div>
                {% empty %}
                <p>投稿がありません。</p>
                {% endfor %}
            </div>
        </div>
    </div>

    {% if is_paginated %}
    <ul class="pagination">
        <!-- 前ページへのリンク -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
             </a>
        </li>
        {% endif %}

        <!-- ページ数表示 -->
        {% for page_num in page_obj.paginator.page_range %}
        {% if page_obj.number == page_num %}
        <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endif %}
        {% endfor %}

        <!-- 次ページへのリンク -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
    {% endif %}
</section>
{% endblock %}

board/templates/board_gakusei.html
{% extends 'base.html' %}

{% load static %}

{% block title %}学内掲示板 - 学生課{% endblock %}

{% block header %}
<div class="col-md-3 text-end">
    {% if user.is_authenticated %}
    {% if request.user.is_staff %}
    <a href="{% url 'board:post_create' %}" class="btn btn-primary float-right">新規作成</a>
    {% endif %}
    <a href="{% url 'account_logout' %}" class="btn btn-primary float-right">LOG OUT</a>
    {% else %}
    <a href="{% url 'account_login' %}" class="btn btn-primary float-right">LOG IN</a>
    {% endif %}
</div>
{% endblock %}

{% block board-title %}学生課{% endblock %}

{% block contents %}
    <div class="container text-center">
        <div class="row justify-content-md-center">
            <div class="col-md-10">
                <div class="alert alert-secondary" role="alert">
                    <div class="mb-3">
                        <label for="exampleSelect" class="form-label">掲示板リスト</label>
                        {% block nav %}
                        <ul class="list-unstyled">
                            <li><a href="{% url 'board:index' %}" title="掲示板トップ" class="text-decoration-none">掲示板トップ</a></li>
                            <li><a href="{% url 'board:board_kyoumu' %}" title="教務課" class="text-decoration-none">教務課</a></li>
                            <li><a href="{% url 'board:board_shien' %}" title="学生支援担当" class="text-decoration-none">学生支援担当</a></li>
                            <li><a href="{% url 'board:board_job' %}" title="就職課" class="text-decoration-none">就職課</a></li>
                            <li><a href="{% url 'board:board_gakuyu' %}" title="学友会" class="text-decoration-none">学友会</a></li>
                            <li><a href="{% url 'board:board_arubaito' %}" title="アルバイト" class="text-decoration-none">アルバイト</a></li>
                        </ul>
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-10">
                <div class="alert alert-secondary" role="alert">
                    <div class="mb-3">
                        <label for="exampleSelect" class="form-label">検索メニュー</label>
                        <form method="GET" class="post-form">
                            {% csrf_token %}
                            {{ search_form.as_p }}
                            <input type="submit" value="検索">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="board py-5 bg-body-tertiary">
        <div class="container">
            <div class="post-title text-center">
                <p>掲示物一覧</p>
            </div>
            <div class="row row-cols-1 row-cols-md-2 g-2">
                {% for post in post_list %}
                <div class="col">
                    <div class="card text-center">
                        <div class="card-header">
                            {{ post.board }}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">
                                {{ post.post_title }}
                            </h5>
                            <p class="card-text">
                                {{ post.post_overview|truncatechars:20 }}
                            </p>
                            <a href="{% url 'board:post_detail' post.pk %}" class="btn btn-primary">詳細表示</a>
                        </div>
                        <div class="card-footer text-body-secondary">
                            {{ post.started_at }}
                        </div>
                    </div>
                </div>
                {% empty %}
                <p>投稿がありません。</p>
                {% endfor %}
            </div>
        </div>
    </div>

    {% if is_paginated %}
    <ul class="pagination">
        <!-- 前ページへのリンク -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
             </a>
        </li>
        {% endif %}

        <!-- ページ数表示 -->
        {% for page_num in page_obj.paginator.page_range %}
        {% if page_obj.number == page_num %}
        <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endif %}
        {% endfor %}

        <!-- 次ページへのリンク -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
    {% endif %}
</section>
{% endblock %}

board/templates/board_gakuyu.html
{% extends 'base.html' %}

{% load static %}

{% block title %}学内掲示板 - 学友会{% endblock %}

{% block header %}
<div class="col-md-3 text-end">
    {% if user.is_authenticated %}
    {% if request.user.is_staff %}
    <a href="{% url 'board:post_create' %}" class="btn btn-primary float-right">新規作成</a>
    {% endif %}
    <a href="{% url 'account_logout' %}" class="btn btn-primary float-right">LOG OUT</a>
    {% else %}
    <a href="{% url 'account_login' %}" class="btn btn-primary float-right">LOG IN</a>
    {% endif %}
</div>
{% endblock %}

{% block board-title %}学友会{% endblock %}

{% block contents %}
    <div class="container text-center">
        <div class="row justify-content-md-center">
            <div class="col-md-10">
                <div class="alert alert-secondary" role="alert">
                    <div class="mb-3">
                        <label for="exampleSelect" class="form-label">掲示板リスト</label>
                        {% block nav %}
                        <ul class="list-unstyled">
                            <li><a href="{% url 'board:index' %}" title="掲示板トップ" class="text-decoration-none">掲示板トップ</a></li>
                            <li><a href="{% url 'board:board_kyoumu' %}" title="教務課" class="text-decoration-none">教務課</a></li>
                            <li><a href="{% url 'board:board_shien' %}" title="学生支援担当" class="text-decoration-none">学生支援担当</a></li>
                            <li><a href="{% url 'board:board_job' %}" title="就職課" class="text-decoration-none">就職課</a></li>
                            <li><a href="{% url 'board:board_gakusei' %}" title="学生課" class="text-decoration-none">学生課</a></li>
                            <li><a href="{% url 'board:board_arubaito' %}" title="アルバイト" class="text-decoration-none">アルバイト</a></li>
                        </ul>
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-10">
                <div class="alert alert-secondary" role="alert">
                    <div class="mb-3">
                        <label for="exampleSelect" class="form-label">検索メニュー</label>
                        <form method="GET" class="post-form">
                            {% csrf_token %}
                            {{ search_form.as_p }}
                            <input type="submit" value="検索">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="board py-5 bg-body-tertiary">
        <div class="container">
            <div class="post-title text-center">
                <p>掲示物一覧</p>
            </div>
            <div class="row row-cols-1 row-cols-md-2 g-2">
                {% for post in post_list %}
                <div class="col">
                    <div class="card text-center">
                        <div class="card-header">
                            {{ post.board }}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">
                                {{ post.post_title }}
                            </h5>
                            <p class="card-text">
                                {{ post.post_overview|truncatechars:20 }}
                            </p>
                            <a href="{% url 'board:post_detail' post.pk %}" class="btn btn-primary">詳細表示</a>
                        </div>
                        <div class="card-footer text-body-secondary">
                            {{ post.started_at }}
                        </div>
                    </div>
                </div>
                {% empty %}
                <p>投稿がありません。</p>
                {% endfor %}
            </div>
        </div>
    </div>

    {% if is_paginated %}
    <ul class="pagination">
        <!-- 前ページへのリンク -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
             </a>
        </li>
        {% endif %}

        <!-- ページ数表示 -->
        {% for page_num in page_obj.paginator.page_range %}
        {% if page_obj.number == page_num %}
        <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endif %}
        {% endfor %}

        <!-- 次ページへのリンク -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
    {% endif %}
</section>
{% endblock %}

board/templates/post_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}学内掲示板 - 掲示削除{% endblock %}

{% block active_post_list %}active{% endblock %}

{% block board-title %}
<h2>掲示削除ページ</h2>
{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row text-center">
        <form method="POST">
            {% csrf_token %}
            <p>本当に削除しますか？</p>
            <button class="btn btn-primary mt-5" type="submit">削除</button>
            <a class="btn btn-secondary mt-5 ml-2" href="{% url 'board:post_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}